name = griddle
description = A griddle 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = griddle-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[footer_base]    = Footer Base

; Stylesheets
stylesheets[all][] = css/layouts/griddle/griddle.layout.css
